server:
  port: 9000

db:
  host: localhost
  name: bookstore
  user.service:
    name: bookservice
    password: xxx

spring:
  datasource:
    url: jdbc:postgresql://${db.host}/${db.name}?stringtype=unspecified
    username: ${db.user.service.name}
    password: ${db.user.service.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
